apiVersion: v1
kind: Secret
metadata:
  name: google-oauth-secret
  namespace: family-reunion
type: Opaque
stringData:
  GOOGLE_CLIENT_ID: "1045426516028-eq3vj3md30paejguu8kdatn7k7pugk76.apps.googleusercontent.com"
  INITIAL_ADMIN_EMAIL: "johnson.derrick@gmail.com"
  INITIAL_ADMIN_NAME: "Derrick Johnson"
