---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stripe-secret
  namespace: family-reunion
spec:
  encryptedData:
    STRIPE_SECRET_KEY: AgA/n+Vu56VgCKD9HWfTxQI+L+FAmilMc85m/YGNKhpkUIzzkFx99f32uNaKSBJ+Vo5pt8zCZFXyctA0VtVHCQhR2WdK2sCWTsKecqKMNC2Yngz9SRgjt6dynYfCrQ0DdOigGO68i6Ne0VYM1Ra3+cs0NMVEei07mV/HF/tzJxVNWXIjLSKHyi4W4oBAmqORAEoChfDC9xqudiFobi6Nm6fjYtBfPveppLLtYfBb2gh8WI9lVrq/eWQXwB6oDFJ26sksGqx5PFnr6xOJXIy8ZW0mGajcXvF1QvB8q1b5RKi+qc8FkMlD1Wi/OMwEBDtQKi9JsypiWi7ksc4qeA12TNU4UxYZkK+d5e8tYoeyetE+k4A7SjLSb64nx6YOhhDL0QQpsOvGMlw7nUJ+3/rif4rMX9A0yKky0tjMpUwSmYXtQxfzvEJiq+iGTNrxnwY7YFrC/66bUkZ7MRBXBMsifMoqYyIeVa5V6KNpH80S+f9quZelgByTV5fmQYhsyNqxDZf5K3QaDGBn6+j9q8okuWAqDuHKDV1Ng5Uh2flQ2VS4QBt0wuPM32QyKdPyEGHQxxltfhzfd0HmmTjGFoy2D0tXVAuyNMTlqC/wzVyl3l0fQeJFEj1EVhwH6QaWpofyRB4duy/LXUll3XlquO+mEx/bEjsvzgXUp2CFVBMtioioxZsiIko4fR2EkpNaWHTeJJHqzT/pMKBCq/bqtO0PdxOsVaItj573RS5FmLk8BNaKrBNInS5pnwsuAqrEi3LPteJWpLjLORCbyzpeJnM+tgvJESXeaBMt1s8iKq2du/Prxv/Nj0C7N3oXzEp+bs8OYFV4hZGvBWcMFewvrA==
    STRIPE_WEBHOOK_SECRET: AgBDaeBshb10d4mXIUvNBcvZMdkwDo91g37mTGtwwclY+LqLIc6rjGDO5BBaKbjHth5IjkqzZKZ5ZroVNOcOULXn0riFVbCSC/kJ8ImuS75hHdGEbSJDuEzqrYTWQWdRLptzP0s0fMY/Zry6HW4qfqbedmDxFi1gn1+A5QNcllHUYP4y6fDY/LKZGOWO2ZSizyOX9OE+0g258aFSlZSi8RpPdBbsSAfbCOyTGUrLShMXSvJwp3Y3Ktf1uF0qPmH8js+DSCrUF0+rj6sHWp9yRB4w/xBksjB4eLZyjsW6ViOcX9Jrb+6BDMVsTTUKWluGxBXVwTrI93pXGkZcfcpN+UbyGBCym2pJqDotobohdKYfjsKJcTDG/zHhQeP57yJT4E+X8doZK/DX6DFh73Ng9WNzY+LG1X7KTJ7h6u0lwBf65uK4WqJtu/ePXoPSNoMUEVL5d/84VmCB46TR6rOJ6ysgXPDck++id0DGKSNsXhSlXmKJWH+0N9idOgIsdP/w7xP80X+xSPh7Jtkqj7INEaLg75ohK0QvhxEG0ZiFGp20BerwgU+JfrQlix7A1nvUVy1VMiKi/Vy/trZAZkLnashHS3Iec6sIy+UtFnP3bxaImF/Xacnykmlq3rCCWCzDUMG+qJRXNmuQrA36hkwpIX5Q46WDdDa1xXMTrrQI5Wis+Qx4uPCgUsmdtKQyh7n2W8kAYH8AMSfimjc6jc2U978CYGYa0uxJrxr/WXcDKrts5QulV556jQ==
  template:
    metadata:
      name: stripe-secret
      namespace: family-reunion
    type: Opaque
