---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stripe-secret
  namespace: family-reunion
spec:
  encryptedData:
    STRIPE_SECRET_KEY: AgCabluRwGWXh1xXPbTxYhvmNEuTZofzj4Z0oPsuOtkjuy1M7ZzqjUc2STr7+7YYxcQme2TiVBlwCJesfZfxlWKa4mB2UgtPiM9g/HZAG6yIxxHcqJkSRiloeyBrfOrwmEcPwAnbSklgUwT7lXIHzyx2jFTuW9vnGyvIgu/sPcpiFsEW+4HL46GCtrDpS2f+8ZIQPGN50Fs2pIXT0ESs5brGfOPz09igZKRo22PKWw3n06MV4k15uwtIAE08R1dapaOixfTdDMJPnMko8dOlR5P8nLnRRT77BYiKXjV5HtjOPP+SGhTBz3x0MHWUOfbK7ZiSzxuQozrpZnJrZTxlif37CX7oLmHAb+A93jQK4ENbiHx+omX7SmQbOWvIVE05EofKvqpIc1l8vOXffjwQ2tzD2+5O0ANtf1vnOG019h0fK3q+EWvi+qkDRPh6MjJOdjnahfM/V6UWUPxuUKKl8au8uCAHDVc5GMGv4/Sm9/UGP+Ew1sgUb5YrvFeof/5tVzO1vdvxpv3gkUIdQ7UpOTfjN2W0SlafqANXzcSsSVWH6oFwIDewn933I3krBuR/hKQE3JrL+b11vg/YEzCab9gjMgipW4XdWp/AEP8VW5M8730+oZwRJsQLv5LjoJPBj7z1JoavCPdRc2O1pah3ePNcbesj8PWnhTI3xaJxd2+odEUqlB7+YzFpR1GQZkZnSQAY71uMyevZBwy/JmUmcSwP5mFTbBpeIA29vbbSOkYcTjL6bo2IElstta2vX20HMVfNTj9MIUtukM/AlYr6IZc9jnD//DGbqRFp6Jpa+zKxLLixMV0YXUfCoGDTod8jt0ZDoDvNmM+CEv+wnw==
    STRIPE_WEBHOOK_SECRET: AgAmEhgnxSmr2BMjaKFQ9q5vc2Z9XsfYXcGrjOubzeBnOcbH3Gi2fZbtW1EI6uNpN7T7XRURj3bbgU08aGRCz/KfN64+hZQ/irQhSrIsqcxAN1+eclUdIcW6lfMxyJFwjexaQW4SCEbw9UyFVtZdVYo+VQr1k4SifUxQ3bRcSI3pc/Wtp4IFwVL+1f0lm2/FK+a9Rh/08BBqdn6SI84btzL9H8br9Wk1ApfN5Gl2pKUa1n9N7Idb1tDdAPyOfeKOnfUnNH5Yd+UC5wLEE+2IXNOyQQLXd+u9Zue3vhMY4trffMqre8yKyz6UPIZfCioTFmti5tcLALKizwAiXvKb1VA/DbqMXl6vOf0pIv3qE692BegpANtSj3Z7MCTY1SQ4Z1D0BSWLxdQ++eHmZbFQcTvo+vVjSZzirHiztB/kGdXa5N2eBaz+AzpZ+B17EAbAVN1UssdzKnSfFgfVSRZJJnFsq3/xjapa3GdNatb9Z0dkKp09dbMCuE9Fg9KO03nSKenFRv/Hn3areMVTfVHawNYar0rN0TNIwyg2+Gj69bGRzjcm+Y9UZnEMNizAXLtWbbXzSPr/7M7gmuOAsrEzxzU3TpZawNaVjgvn9Fkq96WVlozKD6CDAff4Joxf/MmtYL/ww1ORVwIrCvkK21bCrBpL/9x9Sq/94Adu8StdhgEkYnbf6eh5mAnoO/uV/CMWi/lMze8iVzf3zQq/SSczDD87iKVZPfHBJpnUkKBa3RjOylQ06iqttg==
  template:
    metadata:
      name: stripe-secret
      namespace: family-reunion
    type: Opaque
