---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stripe-secret
  namespace: family-reunion
spec:
  encryptedData:
    STRIPE_SECRET_KEY: AgCY0CU1vTRv1wleHrqBJAjKCctvcKBGw/UqFFVfzj5yCIuu8EaxiOaF8eWZLKrmSEKsMxZQCw0QeUJGvu3LbxyiubAgwfUiE+MaXT135fYKwIQz4c23J5XbavROkCT5xGtz/Y6cUvn/Uu1Zh2awOrX0vHIh+7l4f1gHddFFxpGHPvjET8aUEL7v0sXEEL20Wz5T1vsxcKhPQJUhZhmbNVhADmlwmxalKT3e6RZ9Ldm7v/ZMj0UpIYYOG6kvaDHc7n5/PxT/mlmbxR3RywaV9/J/yiVTVhSPmEgDPx7jJOJp9NletX2JTdciaYeHny6DLAgWdRZqQ97Q9qFmjp070WvFK8Ijvwo74VPc9/Jkx7t+E8qzWDqK+wNijzvzT87k/maGSteUPZpJJsfeS1o4itDiHevFK2mEK6P36Tnn0nKBE3m/sWq5xeShOh3C5v6chXzyZOPiTuNmOQPMNZABt5BKPPfgdmaAKqoF1Nml1jtcTSkO27t9Krcicm8HCGTqD607vB2cZXd8dZPZP6Oo7HAdKX/b0xDhZES3sbybymk40Q5te9Kti5cb1kE/d1EOoGfj8T2ee6Qa/+fBiZQaknAUdDZ6no7HhVEG/2hLdsyfDC/PWhJsdAqSWaVdGLgeSg4SomAzKVaVvJAwE+zh2szc/s03XfHdW+0HxSmMWj9JWYHnPmRbLjRI4lIPVQSCfp1MJ+7cdmKJMcca8fA6u9OEO5UN6VBiKW5pXZ8f+huAg0Mf/DBhWFZMDkWdb7jsfF19P+fLPtqma2wB9m9OhNjmTNn5qpHit0SEnuI4htfV+XqTNvZLxZvkIdH+Ux1p7pE0gffFAXm6L1pMqw==
    STRIPE_WEBHOOK_SECRET: AgDlIlkITIHWI3c9xB5INH2SEm8YQ+nP5qARr2eJBw8kQpUM2knosf2nwOUJ+GJ4XPkhqzR6AyrTQXPrYQQq5pqnZTBC2bN0UelbMBXLmaMjLMszeQvpXMJjnd/FjTc9Ctu14gkmAj3VsOVmERoQHxDlY213q6PCzAQkHmib8rD+o3WVHA7dUZYsU9rrpukhVVuhjNqz2ifYYqvQK8nex40S9Jx2IWakAyxQHOith4phg3vGv0BBpv28hnQA+3ZlyJi7vy/7ZAO2HktWXJRC21gvTm2aM4crsbZh7n23NSS8vdpZDxnmwM2eYV7klwzdV77gvU1AWZU25MMps+DpcpmyQfYdUtnEgzLjqYmKo3vu6JqeVyoFsRrUFpLwzUxBlh86ZVKzk/jHOfsm+krOwluKzsfF6YVnhbHavbo8TinzDyNZWD7CWiNCP3Itglmzayal0qRrnXs+wVgNgSD5x3KZ6Kx2iL5MeRMCKILqblIk++1qVDX7ki4wY+LlriY5cv5TXrtDE//CIeUYhPLvdahAMwG2HrkfjeuwvEjHHJsNxN4PNDic67CjRExXST3j4ZJ23dA+OstLx95n7boTFIDlJuw391/GCPuXPN3j8NOtm/86MjyS2db4eWxqwQe4yOlnODitpxeHxJRsK2Ss3wf7qAqDUJcxthhfCvE1F0qyW1hi0DwW9SzCDygdvcoQxqv2emJz4ozqgqQM9kb5EUd9qgr3BSdjBTdF7DRtolkJPfTRg6vU9w==
  template:
    metadata:
      name: stripe-secret
      namespace: family-reunion
    type: Opaque
